### ISSUE TITLE
getting this error 

### ISSUE THREAD

**Issue by DevSaurabh2024** [fireship-io/javascript-millionaire#4]
file:///home/heartbeat/.npm/_npx/aab6981678745c7e/node_modules/firequiz/index.js:151
await welcome();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by codediodeio** [comment]
Check your node version. Make sure it's 14+

**Comment by DevSaurabh2024** [comment]
Thanxx

**Comment by KendallDoesCoding** [comment]
duplicate of #3

**Comment by satr14washere** [comment]
Im running this code on replit but i get the same error how do i update nodejs

**Comment by humanfriend22** [comment]
> Im running this code on replit but i get the same error how do i update nodejs

You'll have to use a Repl with a higher Node version or just run it on a Github Codespace. Just right click `Code` and then the Codespaces tab.
